name: Check for compile errors

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Setup Node.js ${{ matrix.node-version }} environment
        uses: actions/setup-node@v2.5.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm install
          npm run build:prod

      - name: Build documentation
        run: |
          npx typedoc
